config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/shows'
  get 'home/seasons'
  get 'home/episodes'
  get 'home/characters'
  get 'home/quotes'
  resources :shows
  resources :quotes
  resources :episodes
  resources :characters
  root 'shows#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/episode.rb
class Episode < ApplicationRecord
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: %i[ show edit update destroy ]

  # GET /episodes or /episodes.json
  def index
    @episodes = Episode.where(series: params[:series_id], season: params[:season_id])
    #@episodes = Episode.where(series: series_id, season: season_id)
  end

  # GET /episodes/1 or /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes or /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: "Episode was successfully created." }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1 or /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: "Episode was successfully updated." }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1 or /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: "Episode was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.require(:episode).permit(:api_id, :title, :season, :episode, :air_date, :characters, :series)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_with(model: episode) do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
        <% episode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :api_id %>
    <%= form.number_field :api_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.number_field :season %>
  </div>

  <div class="field">
    <%= form.label :episode %>
    <%= form.number_field :episode %>
  </div>

  <div class="field">
    <%= form.label :air_date %>
    <%= form.text_field :air_date %>
  </div>

  <div class="field">
    <%= form.label :characters %>
    <%= form.text_area :characters %>
  </div>

  <div class="field">
    <%= form.label :series %>
    <%= form.text_field :series %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>

      <th>Title</th>
      <th>Season</th>
      <th>Episode</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>

        <td><%= episode.title %></td>
        <td><%= episode.season %></td>
        <td><%= episode.episode %></td>

        <td><%= link_to 'Show', episode %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Episode Code:</strong>
  <%= @episode.api_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @episode.title %>
</p>

<p>
  <strong>Season:</strong>
  <%= @episode.season %>
</p>

<p>
  <strong>Episode:</strong>
  <%= @episode.episode %>
</p>

<p>
  <strong>Air date:</strong>
  <%= @episode.air_date %>
</p>

<p>
  <strong>Chracters:</strong>
  <% @episode.characters.each do |character| %>
      <%= link_to character, controller: "characters", action: "index", character_name: character %>
  <% end %>
</p>

<p>
  <strong>Series:</strong>
  <%= @episode.series %>
</p>