config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/shows'
  get 'home/seasons'
  get 'home/episodes'
  get 'home/characters'
  get 'home/quotes'
  resources :shows
  resources :quotes
  resources :episodes
  resources :characters
  root 'shows#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/character.rb
class Character < ApplicationRecord
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.where(name: params[:character_name])
    @quotes = Quote.where(author: params[:character_name])
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:api_id, :name, :occupation, :img, :status, :nickname, :appearance, :better_call_saul_appearance, :portrayed, :category)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :api_id %>
    <%= form.number_field :api_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :occupation %>
    <%= form.text_area :occupation %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname %>
  </div>

  <div class="field">
    <%= form.label :appearance %>
    <%= form.text_area :appearance %>
  </div>

  <div class="field">
    <%= form.label :better_call_saul_appearance %>
    <%= form.text_area :better_call_saul_appearance %>
  </div>

  <div class="field">
    <%= form.label :portrayed %>
    <%= form.text_field :portrayed %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_area :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>
<h2>Quotes</h2>

<table>
  <thead>
    <tr>
      <th>Character ID</th>
      <th>Name</th>
      <th>Occupation</th>
      <th>Img</th>
      <th>Status</th>
      <th>Nickname</th>
      <th>Appearance</th>
      <th>Better call saul appearance</th>
      <th>Portrayed</th>
      <th>Category</th>
      <th>Quotes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.api_id %></td>
        <td><%= character.name %></td>
        <td><%= character.occupation %></td>
        <td><%= image_tag character.img %></td>
        <td><%= character.status %></td>
        <td><%= character.nickname %></td>
        <td><% character.appearance.each do |appearance| %>
          <%= link_to appearance,  controller: "episodes", action: "index", season_id: appearance, series_id: "Breaking Bad"  %>
        <% end %></td>
        <td><% character.better_call_saul_appearance.each do |better_call_saul_appearance| %>
          <%= link_to better_call_saul_appearance,  controller: "episodes", action: "index", season_id: better_call_saul_appearance, series_id: "Better Call Saul"  %>
        <% end %></td>
        <td><%= character.portrayed %></td>
        <td><%= character.category %></td>
        
        <% @quotes.each do |quote| %>
          <%= quote.quote %>
        <% end %>
        <td><%= link_to 'Show', character %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Api:</strong>
  <%= @character.api_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @character.occupation %>
</p>

<p>
  <strong>Img:</strong>
  <%= @character.img %>
</p>

<p>
  <strong>Status:</strong>
  <%= @character.status %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @character.nickname %>
</p>

<p>
  <strong>Appearance:</strong>
  <%= @character.appearance %>
</p>

<p>
  <strong>Better call saul appearance:</strong>
  <%= @character.better_call_saul_appearance %>
</p>

<p>
  <strong>Portrayed:</strong>
  <%= @character.portrayed %>
</p>

<p>
  <strong>Category:</strong>
  <%= @character.category %>
</p>