config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/shows'
  get 'home/seasons'
  get 'home/episodes'
  get 'home/characters'
  get 'home/quotes'
  resources :shows
  resources :quotes
  resources :episodes
  resources :characters
  root 'shows#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/show.rb
class Show < ApplicationRecord
    #has_many :episodes, characters, quotes dependent: :destroy
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: %i[ show edit update destroy ]

  # GET /shows or /shows.json
  def index
    @shows_service = GlobalShows.new
    @shows_service.save_episodes
    @shows_service.save_characters
    @shows_service.save_quotes
    #@shows = Episode.distinct.pluck(:series)
    #@shows = Episode.select('season,series').distinct
  end

  # GET /shows/1 or /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows or /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: "Show was successfully created." }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1 or /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: "Show was successfully updated." }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1 or /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: "Show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])


    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:api_id, :title, :seasons, :episodes)
    end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_with(model: show) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :api_id %>
    <%= form.number_field :api_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :seasons %>
    <%= form.text_area :seasons %>
  </div>

  <div class="field">
    <%= form.label :episodes %>
    <%= form.text_area :episodes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shows</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Season</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% Episode.select("series, season").group("series, season").each do |show| %>
      <tr>
        <td><%= show.series %></td>
        <td><%= link_to show.season,  controller: "episodes", action: "index", season_id: show.season, series_id: show.series  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Api:</strong>
  <%= @show.api_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @show.title %>
</p>

<p>
  <strong>Seasons:</strong>
  <%= @show.seasons %>
</p>

<p>
  <strong>Episodes:</strong>
  <%= @show.episodes %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>